Make finding the highest bids automatic
abakus-ntnu/charitystream pull request #13
Opened 2021-10-01 18:08 UTC by AdrianAndersen

With this PR, we aggregate the bids to find the current highest bids.
This makes it easier to delete bids in the future,
as you only need to remove a bid from the Bid table.

Furthermore, I added some validation to make it harder to submit "troll" bids. The current maximum bid is set to 10 000 NOK as this is quite much more than the historical maximum. Feel free to comment if you want to dispute this.

Lastly, I made the _api/state/_ endpoint use _Promise.all([...])_ to do all its requests. This should vastly increase the loading time, as we can do the DB requests in parallel. The downside however is that if one request fails, nothing gets returned by the request. This will probably not be an issue tho, as the state is frequently reloaded.

2021-10-01 19:41 UTC, LudvigHz requested changes

2021-10-01 19:41 UTC, LudvigHz commented on components/AuctionItems.js
> +        const errorMessage = "\n Feilmelding: " + (await res.json()).error;
string interpolate pls?

2021-10-01 19:41 UTC, LudvigHz commented on components/AuctionItems.js
> +        const errorMessage = "\n Feilmelding: " + (await res.json()).error;
Is the thought just to print the json?? doesn't really sound very readable to me

2021-10-01 19:41 UTC, LudvigHz commented on pages/api/bid.js
> +      if (bid.amount > MAX_BID_AMOUNT) {
You should also get the highest bid here and make sure the posted bid is higher than that

2021-10-01 19:41 UTC, LudvigHz commented on components/AuctionItems.js
> +    } else if (formData.amount > MAX_BID_AMOUNT) {
You can also use the current highest bid here to validate here as well maybe?? Or not really neccessary if we do it in the backend.

2021-10-01 19:41 UTC, LudvigHz commented on pages/api/state.js
> +    ]);
Nice :100: :speedboat:

2021-10-01 21:36 UTC, AdrianAndersen commented on components/AuctionItems.js
> +    } else if (formData.amount > MAX_BID_AMOUNT) {
If I understand you correctly, this validation is done on line 42-50.
(activeItem.price is the current highest bid) I agree that this should be validated in the backend tho.

2021-10-01 21:40 UTC, AdrianAndersen commented on components/AuctionItems.js
> +        const errorMessage = "\n Feilmelding: " + (await res.json()).error;
This only prints the actual response message from the backend if the response is not OK. The response contains an object:
{error: "foobar"}

I added the error message to provide extra feedback to the user.

2021-10-01 22:03 UTC, AdrianAndersen commented on pages/api/bid.js
> +      if (bid.amount > MAX_BID_AMOUNT) {
Fixed. However, this does not really matter, as the way we get the highest bid just ignores the lower ones. However, it is nice to not get a lot of junk bids in the DB.

2021-10-01 22:20 UTC, LudvigHz commented on pages/api/bid.js
> +      const highestBid = await Bid.find({ id: bid.item })
This doesn't make sense 🤔. Should it not be `auction: req.body.auction` or something?

2021-10-01 22:27 UTC, AdrianAndersen commented on pages/api/bid.js
> +      const highestBid = await Bid.find({ id: bid.item })
No, this should be correct. The reason it is this way, is because I made changes to what _auction_ is. 

Right now, the auction table only contains _id_ and _description_

The highest bid is not stored explicitly in the db, but instead, I use a query to find the maximum bids for each item. (in api/state/)

In this case, this works because it first finds all bids that match the _item_ in the req.bod (Bid) Then, it sorts by amount (DESC) and selects the first element (highest price). 

Are we on the same page now? 😅

2021-10-01 22:36 UTC, AdrianAndersen commented on pages/api/bid.js
> +      const highestBid = await Bid.find({ id: bid.item })
Ah, well spotted! It should have been _item: bid.item_

2021-10-02 08:42 UTC, LudvigHz approved these changes
Lgtm

2021-10-02 09:00 UTC, merged